FROM igitman/nemo-skills:0.6.1

RUN mkdir -p /opt/NeMo-Skills/requirements
COPY setup.py README.md /opt/NeMo-Skills/
COPY nemo_skills /opt/NeMo-Skills/nemo_skills/
COPY requirements /opt/NeMo-Skills/requirements/
RUN cd /opt/NeMo-Skills && pip install -e .[all]


WORKDIR /agentless

RUN git clone -b feat/skills https://github.com/SeanNaren/Agentless.git .
RUN pip install -r requirements.txt
RUN pip install .
