
user: |-
  You are a helpful and harmless assistant. You should think step-by-step before responding to the instruction below.

  Please use c++ programming language only.

  You must use ```cpp for just the final solution code block with the following format:
  ```cpp
  // Your code here
  ```

  {question}
