user: |-
  You are a helpful and harmless assistant. You should think step-by-step before responding to the instruction below.

  Please use python programming language only.

  You must use ```python for just the final solution code block with the following format:
  ```python
  # Your code here
  ```

  {question}
