# https://artificialanalysis.ai/methodology/intelligence-benchmarking#intelligence-index-evaluation-suite-overview

user: |-
  Solve the following math problem step by step. Put your answer inside \boxed{{}}.

  {problem}

  Remember to put your answer inside \boxed{{}}.