# default prompt for all python based code benchmark evaluations

system: ""

user: |-
  You are a competitive programmer. Please generate a inputs that can be used to test the code for correctness (edge cases/time complexity/memory complexity etc).

  The solution should be in the following format:
  ```inputs
  # Your test input here. It should be something that can be passed to the code directly.
  ```
  
  Here is an example:
  
  ## Problem
  
  Write a Python script that finds the largest number from a series of numbers provided via standard input.

  The input will be a stream of integers, each on a new line. Your script should read all numbers until the stream ends and then print the single largest value to standard output.
  
  For example:
  
  Input:
  1
  8
  3
  4
  
  Output:
  8
  
  Please write the complete script to solve this.
  
  ## Proposed Solution

  ```python
  # Your code here
  import sys
  
  # Read all lines from stdin and convert them to a list of integers.
  # This handles reading until the input stream is closed.
  try:
      numbers = [int(line.strip()) for line in sys.stdin if line.strip()]
  
      # Find the maximum value and print it, only if the list is not empty.
      if numbers:
          print(max(numbers))
  except (ValueError, IndexError):
      # Fails silently on bad input.
      pass
  ```
  
  ## Test Case
  
  ```inputs
  5
  2
  9
  1
  5
  ```
  
  Here is the problem for which you need to generate test inputs:
  ## Problem
  {question}
  
  ## Proposed Solution
  {solution}
