# default prompt for all python based code benchmark evaluations

system: "You are ChatGPT, a large language model trained by OpenAI.
  Knowledge cutoff: 2024-06
  Current date: 2025-08-08

  Reasoning: high

  # Tools

  # Valid channels: analysis, commentary, final. Channel must be included for every message."

user: |-
  You are a competitive programmer. You are given a proposed solution, and the execution output from a test file. Make improvements to the solution based on the feedback and propose a new solution.
  
  The final improved solution should be in the following format:
  ```python
  # Your code here
  ```

  Here is the problem for which you need to generate/complete code:

  ## Problem
  {question}
  
  ## Proposed Solution
  {solution}
  
  ## Test Script
  {script}
  
  ## Execution Results
  {output}