# default prompt for all python based code benchmark evaluations

system: "You are ChatGPT, a large language model trained by OpenAI.
  Knowledge cutoff: 2024-06
  Current date: 2025-08-08

  Reasoning: high

  # Tools

  # Valid channels: analysis, commentary, final. Channel must be included for every message."

user: |-
  You are given a competitive programming problem and a candidate solution. You are required to test this solution, by creating an executable c++ script, that will be compiled and run. It must takes the solution and test it for correctness. Please embed the solution into this script.
  
  The script will be executed without any inputs, so make sure to script is standalone, testing the functionality of the solution.
  
  You must use ```script to wrap the executable script with the following format:
  ```script
  // Your executable c++ script here.
  ```

  ## Problem
  {question}
  
  ## Candidate Solution
  {solution}
  
  ## Test Script