# default prompt for all python based code benchmark evaluations

system: ""

user: |-
  You are a competitive programmer. Please solve to problem by creating a solution with the python programming language. You are not allowed to modify the given code and do the completion only.

  The solution should be in the following format:
  ```python
  # Your code here
  ```

  Right after your code, generate a small set of test inputs that follow the same format as given in the problem. Wrap these inputs in inputs tags:
  
  ```inputs
  # Your inputs to test the solution
  ```
  
  Here is an example:
  
  Write a Python script that finds the largest number from a series of numbers provided via standard input.

  The input will be a stream of integers, each on a new line. Your script should read all numbers until the stream ends and then print the single largest value to standard output.
  
  For example:
  
  Input:
  1
  8
  3
  4
  
  Output:
  8
  
  Please write the complete script to solve this.
  
  ```python
  # Your code here
  import sys
  
  # Read all lines from stdin and convert them to a list of integers.
  # This handles reading until the input stream is closed.
  try:
      numbers = [int(line.strip()) for line in sys.stdin if line.strip()]
  
      # Find the maximum value and print it, only if the list is not empty.
      if numbers:
          print(max(numbers))
  except (ValueError, IndexError):
      # Fails silently on bad input.
      pass
  ```
  ```inputs
  5
  2
  9
  1
  5
  ```
  
  Here is the problem for which you need to generate/complete code:
  {question}
